---
title: "Phydro light response"
author: "Jaideep Joshi"
date: "2024-02-17"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(rphydro)
library(tidyverse)
library(ggplot2)
library(reshape2)
```

```{r}
kphio = 0.087;        # quantum yield efficiency
ppfd = 300;          # umol/m2/s
ppfd_max = 1200;
vpd  = 1000;         # Pa
co2  = 400;          # ppm
elv  = 0;            # m.a.s.l.
fapar = 0.7;         # fraction
rdark = 0.015;
tc = 25;
vwind = 3;
netrad = ppfd/2
psi_soil = -0.05
pa = calc_patm(elv)

par_cost = list(alpha=0.1, gamma=1);
par_plant = list(conductivity=3e-17, psi50=-2, b=2);
options = list(gs_method = "GS_IGF", 
               et_method = "ET_DIFFUSION",
               ftemp_vj_method = "FV_kumarathunge19",
               ftemp_rd_method = "FR_heskel16",
               ftemp_br_method = "FB_atkin15",
               scale_alpha = F)
```

## Acclimating response

```{r}
dat = tibble(ppfd = seq(0,1200,length.out=50)) %>% mutate(dat = purrr::map(.x=ppfd, .f = ~rphydro_analytical(tc, tc, .x, netrad, vpd, co2, pa, fapar, kphio, psi_soil, rdark, vwind, par_plant, par_cost, options))) %>% unnest_wider(dat)
```

```{r}
df.m <- dat %>% melt("ppfd")

ggplot(df.m, aes(y=value, x=ppfd)) + 
  geom_line(col="aquamarine4") + 
  theme_classic() +
  theme(strip.background = element_rect(color = "white", size = 1))+
  facet_wrap(~variable, scales = "free")

```

## Instantaneous response

```{r}
acc = dat %>% filter(ppfd == 1200)

dat_inst = tibble(ppfd = seq(0,1200,length.out=50)) %>% mutate(dat = purrr::map(.x=ppfd, .f = ~rphydro_instantaneous_analytical(acc$vcmax25, acc$jmax25, tc, tc, .x, netrad, vpd, co2, pa, fapar, kphio, psi_soil, rdark, vwind, par_plant, par_cost, options))) %>% unnest_wider(dat)

df.m1 <- dat_inst %>% melt("ppfd")

ggplot(df.m1, aes(y=value, x=ppfd)) + 
  geom_line(col="aquamarine4") + 
  geom_vline(xintercept = 0, col="pink") + 
  theme_classic() +
  theme(strip.background = element_rect(color = "white", size = 1))+
  facet_wrap(~variable, scales = "free")

```


### Compare ac, aj, in inst responses

```{r}
dat_inst %>% select(ac, aj, isVcmaxLimited) %>% mutate(isVcmaxLimited = isVcmaxLimited*5) %>%  matplot(x=dat_inst$ppfd, type="l", lty=1, col=c("green4", "yellow3", "black"))
abline(v=0, col="pink")
```

### J vs ppfd

```{r}
tibble(ppfd = seq(0,1200, length.out=50)) %>% 
  mutate(J = kphio*ppfd/sqrt(1+(4*kphio*ppfd/acc$jmax)^2)) %>% 
  ggplot(aes(x=ppfd, y=J))+
  geom_line()
  

```


### Subdaily response

```{r}
dat_acc = tibble(ppfd = ppfd_max) %>% mutate(dat = purrr::map(.x=ppfd, .f = ~rphydro_analytical(tc, tc, .x, netrad, vpd, co2, pa, fapar, kphio, psi_soil, rdark, vwind, par_plant, par_cost, options))) %>% unnest_wider(dat)


dat_subd = tibble(t = seq(0,pi,length.out=50)) %>% mutate(ppfd = ppfd_max*sin(t)) %>% mutate(dat = purrr::map(.x=ppfd, .f = ~rphydro_instantaneous_analytical(dat_acc$vcmax25, dat_acc$jmax25, tc, tc, .x, netrad, vpd, co2, pa, fapar, kphio, psi_soil, rdark, vwind, par_plant, par_cost, options))) %>% unnest_wider(dat)

dat_subd %>% pivot_longer(-ppfd) %>%  ggplot(aes(y=value, x=ppfd)) + 
  geom_line(col="aquamarine4") + 
  geom_vline(xintercept = 0, col="pink") + 
  theme_classic() +
  theme(strip.background = element_rect(color = "white", size = 1))+
  facet_wrap(~name, scales = "free")

df.m1.subd <- dat_subd %>% pivot_longer(-t)

df.m1.subd_mean = df.m1.subd %>% group_by(name) %>% summarize(value_mean=mean(value))

df.m1.subd %>% 
  left_join(df.m1.subd_mean) %>% 
  ggplot() + 
  geom_line(aes(y=value, x=t), col="aquamarine4") + 
  geom_hline(aes(yintercept=value_mean), col="pink")+
  theme_classic() +
  theme(strip.background = element_rect(color = "white", size = 1))+
  facet_wrap(~name, scales = "free")


```


### Daily scaling options

We test several methods for scaling the acclimating model response from daily-max ppfd to daily-mean ppfd.

```{r}
ppfd_max = ppfd_max
ppfd_daytime = mean(dat_subd$ppfd)
ppfd_24hr = ppfd_daytime/2
```

```{r}
## Actual daily mean
dat_inst_actual = df.m1.subd_mean %>% 
  pivot_wider(names_from=name, values_from=value_mean) %>% 
  mutate(across(
    everything(),
    function(x){x/2}
  )) %>% 
  mutate(type = "actual")

## Inst model with linear scaling
dat_inst_linear = dat_acc %>% 
  mutate(across(
    everything(),
    function(x){x*ppfd_24hr/ppfd_max}
  )) %>% 
  mutate(type="linear")

# Inst model with daytime ppfd
dat_inst_phydro_day = rphydro_instantaneous_analytical(dat_acc$vcmax25, dat_acc$jmax25, tc, tc, ppfd_daytime, netrad, vpd, co2, pa, fapar, kphio, psi_soil, rdark, vwind, par_plant, par_cost, options) %>%
  as.data.frame() %>% 
  mutate(across(
    everything(),
    function(x){x/2}
  )) %>% 
  mutate(type="inst_daytime")

# Inst model with daytime ppfd and acclimated dpsi
dat_inst_phydro_day_dpsi = rphydro_instantaneous_analytical_given_dpsi(acc$dpsi, dat_acc$vcmax25, dat_acc$jmax25, tc, tc, ppfd_daytime, netrad, vpd, co2, pa, fapar, kphio, psi_soil, rdark, vwind, par_plant, par_cost, options) %>%
  as.data.frame() %>% 
  mutate(across(
    everything(),
    function(x){x/2}
  )) %>% 
  mutate(type="inst_daytime_accdpsi")

# Inst model with 24hr ppfd
dat_inst_phydro_24hr = rphydro_instantaneous_analytical(dat_acc$vcmax25, dat_acc$jmax25, tc, tc, ppfd_24hr, netrad, vpd, co2, pa, fapar, kphio, psi_soil, rdark, vwind, par_plant, par_cost, options) %>%
  as.data.frame() %>% 
  mutate(type="inst_24hr")


```

### Compare daily predictions

```{r fig.width=9, fig.height=9}
dplyr::bind_rows(
  dat_inst_actual,
  dat_inst_linear,
  dat_inst_phydro_day,
  dat_inst_phydro_day_dpsi,
  dat_inst_phydro_24hr
) %>% 
  pivot_longer(-type) %>% 
  ggplot(aes(y=type, x=value, fill=type))+
    geom_col(position="dodge")+
    facet_wrap(~name, scales="free_x")
    
```

